import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="layout-body">
        <div className="content-frame">
          <nav className="container">
            <h3>BP</h3>
            <ul className="nav">
              <li>
                <a href="/">Home</a>
              </li>
              <li>
                <a href="/project-index">Projects</a>
              </li>
              <li>
                <a href="/about">About</a>
              </li>
              <li>
                <a href="/contact">Contact</a>
              </li>
            </ul>
          </nav>
          <div className="main-content">{children}</div>
          <footer className="footer">
            <p>Copyright &copy; BP</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
